### ISSUE TITLE
diseñar base de datos para tipos documentales

### ISSUE THREAD

**Issue by jairomelo** [neogranadina/neo_escan#5]
- [x]  diseñar la estructura de datos
- [x]  recuperar los datos de cada formulario para poblar las tablas de la db
- [x]  leer las tablas desde la app (interface de visualización de proyectos y "escáner")

**Comment by juancobo** [comment]
Buenísimo! En relación a esto quisiera que hablemos acerca de optimizar para luego facilitar la importación de los resultados a lo que vayamos a usar (Omeka?) para control de calidad y descripción.
