### ISSUE TITLE
Lista de correcciones y mejoras 

### ISSUE THREAD

**Issue by jairomelo** [neogranadina/neo_escan#8]
- [x] Asegurar compatibilidad con CHDK 1.5
- [x] Eliminar requisito de folios
- [x] Nombre de archivo automatizado (pares e impares)
- [x] Minimizar los condicionales para el uso de dos cámaras. Evitar que se reinicie la aplicación.
- [x] Permitir el funcionamiento con una sola cámara.
- [x] Cerrar proyecto debe cambiar de "rec" a "play" (chdkptp)
- [x] Crear ejecutable
- [x] Crear cámara izquierda y derecha
- [x] Adoptar [Baglt](https://en.wikipedia.org/wiki/BagIt) como esquema de datos
- [x] Deprecated: botón validación.
- [x] No borrar a negro las imágenes (eliminar el botón validación ajusta ese issue)
- [x] #16
- [x] #17
- [x] #19
- [x] Editar metadatos OK
- [x] Editar configuración
- [x] Archivo de metadatos en json en el archivo de cada proyecto
- [x] Arreglar eliminar proyecto
- [x] Arreglar contador de imágenes

Con Pyside2
- [x] Abrir en pantalla completa
- [x] Asegurar que la barra de espacio haga la captura y validación de la foto. (ESC acciona "retomar")
- [x] #18

De la imagen
- [x] Deshabilitar el permiso SSH de la imagen

**Comment by juancobo** [comment]
- [ ] Hay que resolver lo del orden de las cámaras. Aún no hay manera de fijar cuál es la par y cuál es la impar, y ten en cuenta que en rionegro ya tienen fijadas las cámaras y no se pueden cambiar de lado. En mi caso están al revés.

- [ ] Hay que organizar lo de la rotación, porque las imágenes no están quedando volteadas. Es decir, hay que rotar una 90º y la otra 270º. Spreads lo hacía a partir del EXIF de cada imagen, si no recuerdo mal.  

- [ ] Algo que debe ser más sencillo de resolver es cómo aparecen las previsualizaciones. Supongo que depende de la resolución y tamaño del monitor, pero en todo caso deberían estar en “fit” y no en “stretch”. Es decir, que salga en proporción 3:4 (o 4:3), que es la original, y no 1:1, como sale ahora. 

-[ ] Me encanta que ya no salgan imágenes negras sino que te muestre las últimas, pero ¿podemos quitar lo de continuar? Ya no hace falta. Es decir, tener un botón de capturar y uno de retomar que haga una nueva captura y elimine las últimas dos imágenes, siguiendo la secuencia. 

- [ ] Todavía no funciona el pedal — creo que está mapeado a la tecla "D" por default.

- [ ] Sigue lento — en algunos casos toma 15 segundos en aparecer las imágenes, y a veces toma una tercera foto (dispara una de las cámaras una segunda vez). ¿Quizás aumentar el tiempo entre una toma y la otra para que tenga tiempo de transferir? 

- [ ] Sería bueno tener un overlay o una pantalla de "capturando" o "procesando" mientras toma las imagenes, que de paso te bloquee el teclado y el mouse para que no te pegues a presionar el botón de capturar más veces.

**Comment by jairomelo** [comment]
Todos los issues corregidos 🥳
